// Generated by jextract
package io.ygdrasil.wgpu.internal.jna

import java.lang.foreign.AddressLayout
import java.lang.foreign.Arena
import java.lang.foreign.GroupLayout
import java.lang.foreign.MemoryLayout.Companion.sequenceLayout
import java.lang.foreign.MemoryLayout.Companion.structLayout
import java.lang.foreign.MemoryLayout.PathElement.groupElement
import java.lang.foreign.MemorySegment
import java.lang.foreign.SegmentAllocator
import java.lang.foreign.ValueLayout
import java.util.function.Consumer

/**
 * {@snippet lang=c :
 * * struct WGPUBufferBindingLayout {
 * *     const WGPUChainedStruct *nextInChain;
 * *     WGPUBufferBindingType type;
 * *     WGPUBool hasDynamicOffset;
 * *     uint64_t minBindingSize;
 * * }
 * * }
 */
object WGPUBufferBindingLayout {
    private val `$LAYOUT` = structLayout(
        wgpu_h.C_POINTER.withName("nextInChain"),
        wgpu_h.C_INT.withName("type"),
        wgpu_h.C_INT.withName("hasDynamicOffset"),
        wgpu_h.C_LONG_LONG.withName("minBindingSize")
    ).withName("WGPUBufferBindingLayout")

    /**
     * The layout of this struct
     */
    @JvmStatic
    fun layout(): GroupLayout {
        return `$LAYOUT`
    }

    private val `nextInChain$LAYOUT`: AddressLayout = `$LAYOUT`.select(groupElement("nextInChain")) as AddressLayout

    /**
     * Layout for field:
     * {@snippet lang=c :
     * * const WGPUChainedStruct *nextInChain
     * * }
     */
    fun `nextInChain$layout`(): AddressLayout {
        return `nextInChain$LAYOUT`
    }

    private const val `nextInChain$OFFSET`: Long = 0

    /**
     * Offset for field:
     * {@snippet lang=c :
     * * const WGPUChainedStruct *nextInChain
     * * }
     */
    fun `nextInChain$offset`(): Long {
        return `nextInChain$OFFSET`
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * * const WGPUChainedStruct *nextInChain
     * * }
     */
    fun nextInChain(struct: MemorySegment): MemorySegment {
        return struct.get(`nextInChain$LAYOUT`, `nextInChain$OFFSET`)
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * * const WGPUChainedStruct *nextInChain
     * * }
     */
    fun nextInChain(struct: MemorySegment, fieldValue: MemorySegment?) {
        struct.set(
            `nextInChain$LAYOUT`, `nextInChain$OFFSET`,
            fieldValue!!
        )
    }

    private val `type$LAYOUT` = `$LAYOUT`.select(groupElement("type")) as ValueLayout.OfInt

    /**
     * Layout for field:
     * {@snippet lang=c :
     * * WGPUBufferBindingType type
     * * }
     */
    fun `type$layout`(): ValueLayout.OfInt {
        return `type$LAYOUT`
    }

    private const val `type$OFFSET`: Long = 8

    /**
     * Offset for field:
     * {@snippet lang=c :
     * * WGPUBufferBindingType type
     * * }
     */
    fun `type$offset`(): Long {
        return `type$OFFSET`
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * * WGPUBufferBindingType type
     * * }
     */
    fun type(struct: MemorySegment): Int {
        return struct.get(`type$LAYOUT`, `type$OFFSET`)
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * * WGPUBufferBindingType type
     * * }
     */
    fun type(struct: MemorySegment, fieldValue: Int) {
        struct.set(`type$LAYOUT`, `type$OFFSET`, fieldValue)
    }

    private val `hasDynamicOffset$LAYOUT` = `$LAYOUT`.select(groupElement("hasDynamicOffset")) as ValueLayout.OfInt

    /**
     * Layout for field:
     * {@snippet lang=c :
     * * WGPUBool hasDynamicOffset
     * * }
     */
    fun `hasDynamicOffset$layout`(): ValueLayout.OfInt {
        return `hasDynamicOffset$LAYOUT`
    }

    private const val `hasDynamicOffset$OFFSET`: Long = 12

    /**
     * Offset for field:
     * {@snippet lang=c :
     * * WGPUBool hasDynamicOffset
     * * }
     */
    fun `hasDynamicOffset$offset`(): Long {
        return `hasDynamicOffset$OFFSET`
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * * WGPUBool hasDynamicOffset
     * * }
     */
    fun hasDynamicOffset(struct: MemorySegment): Int {
        return struct.get(`hasDynamicOffset$LAYOUT`, `hasDynamicOffset$OFFSET`)
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * * WGPUBool hasDynamicOffset
     * * }
     */
    fun hasDynamicOffset(struct: MemorySegment, fieldValue: Int) {
        struct.set(`hasDynamicOffset$LAYOUT`, `hasDynamicOffset$OFFSET`, fieldValue)
    }

    private val `minBindingSize$LAYOUT` = `$LAYOUT`.select(groupElement("minBindingSize")) as ValueLayout.OfLong

    /**
     * Layout for field:
     * {@snippet lang=c :
     * * uint64_t minBindingSize
     * * }
     */
    fun `minBindingSize$layout`(): ValueLayout.OfLong {
        return `minBindingSize$LAYOUT`
    }

    private const val `minBindingSize$OFFSET`: Long = 16

    /**
     * Offset for field:
     * {@snippet lang=c :
     * * uint64_t minBindingSize
     * * }
     */
    fun `minBindingSize$offset`(): Long {
        return `minBindingSize$OFFSET`
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * * uint64_t minBindingSize
     * * }
     */
    fun minBindingSize(struct: MemorySegment): Long {
        return struct.get(`minBindingSize$LAYOUT`, `minBindingSize$OFFSET`)
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * * uint64_t minBindingSize
     * * }
     */
    fun minBindingSize(struct: MemorySegment, fieldValue: Long) {
        struct.set(`minBindingSize$LAYOUT`, `minBindingSize$OFFSET`, fieldValue)
    }

    /**
     * Obtains a slice of `arrayParam` which selects the array element at `index`.
     * The returned segment has address `arrayParam.address() + index * layout().byteSize()`
     */
    fun asSlice(array: MemorySegment, index: Long): MemorySegment {
        return array.asSlice(layout().byteSize() * index)
    }

    /**
     * The size (in bytes) of this struct
     */
    fun sizeof(): Long {
        return layout().byteSize()
    }

    /**
     * Allocate a segment of size `layout().byteSize()` using `allocator`
     */
    fun allocate(allocator: SegmentAllocator): MemorySegment {
        return allocator.allocate(layout())
    }

    /**
     * Allocate an array of size `elementCount` using `allocator`.
     * The returned segment has size `elementCount * layout().byteSize()`.
     */
    fun allocateArray(elementCount: Long, allocator: SegmentAllocator): MemorySegment {
        return allocator.allocate(sequenceLayout(elementCount, layout()))
    }

    /**
     * Reinterprets `addr` using target `arena` and `cleanupAction` (if any).
     * The returned segment has size `layout().byteSize()`
     */
    fun reinterpret(addr: MemorySegment, arena: Arena, cleanup: Consumer<MemorySegment?>): MemorySegment {
        return reinterpret(addr, 1, arena, cleanup)
    }

    /**
     * Reinterprets `addr` using target `arena` and `cleanupAction` (if any).
     * The returned segment has size `elementCount * layout().byteSize()`
     */
    fun reinterpret(
        addr: MemorySegment,
        elementCount: Long,
        arena: Arena,
        cleanup: Consumer<MemorySegment?>
    ): MemorySegment {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup)
    }
}

