// Generated by jextract
package io.ygdrasil.wgpu.internal.jna

import java.lang.foreign.AddressLayout
import java.lang.foreign.Arena
import java.lang.foreign.GroupLayout
import java.lang.foreign.MemoryLayout.Companion.sequenceLayout
import java.lang.foreign.MemoryLayout.Companion.structLayout
import java.lang.foreign.MemoryLayout.PathElement.groupElement
import java.lang.foreign.MemorySegment
import java.lang.foreign.SegmentAllocator
import java.lang.foreign.ValueLayout
import java.util.function.Consumer

/**
 * {@snippet lang=c :
 * * struct WGPUComputePassTimestampWrites {
 * *     WGPUQuerySet querySet;
 * *     uint32_t beginningOfPassWriteIndex;
 * *     uint32_t endOfPassWriteIndex;
 * * }
 * * }
 */
object WGPUComputePassTimestampWrites {
    private val `$LAYOUT` = structLayout(
        wgpu_h.C_POINTER.withName("querySet"),
        wgpu_h.C_INT.withName("beginningOfPassWriteIndex"),
        wgpu_h.C_INT.withName("endOfPassWriteIndex")
    ).withName("WGPUComputePassTimestampWrites")

    /**
     * The layout of this struct
     */
    fun layout(): GroupLayout {
        return `$LAYOUT`
    }

    private val `querySet$LAYOUT`: AddressLayout = `$LAYOUT`.select(groupElement("querySet")) as AddressLayout

    /**
     * Layout for field:
     * {@snippet lang=c :
     * * WGPUQuerySet querySet
     * * }
     */
    fun `querySet$layout`(): AddressLayout {
        return `querySet$LAYOUT`
    }

    private const val `querySet$OFFSET`: Long = 0

    /**
     * Offset for field:
     * {@snippet lang=c :
     * * WGPUQuerySet querySet
     * * }
     */
    fun `querySet$offset`(): Long {
        return `querySet$OFFSET`
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * * WGPUQuerySet querySet
     * * }
     */
    fun querySet(struct: MemorySegment): MemorySegment {
        return struct.get(`querySet$LAYOUT`, `querySet$OFFSET`)
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * * WGPUQuerySet querySet
     * * }
     */
    fun querySet(struct: MemorySegment, fieldValue: MemorySegment?) {
        struct.set(
            `querySet$LAYOUT`, `querySet$OFFSET`,
            fieldValue!!
        )
    }

    private val `beginningOfPassWriteIndex$LAYOUT` =
        `$LAYOUT`.select(groupElement("beginningOfPassWriteIndex")) as ValueLayout.OfInt

    /**
     * Layout for field:
     * {@snippet lang=c :
     * * uint32_t beginningOfPassWriteIndex
     * * }
     */
    fun `beginningOfPassWriteIndex$layout`(): ValueLayout.OfInt {
        return `beginningOfPassWriteIndex$LAYOUT`
    }

    private const val `beginningOfPassWriteIndex$OFFSET`: Long = 8

    /**
     * Offset for field:
     * {@snippet lang=c :
     * * uint32_t beginningOfPassWriteIndex
     * * }
     */
    fun `beginningOfPassWriteIndex$offset`(): Long {
        return `beginningOfPassWriteIndex$OFFSET`
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * * uint32_t beginningOfPassWriteIndex
     * * }
     */
    fun beginningOfPassWriteIndex(struct: MemorySegment): Int {
        return struct.get(`beginningOfPassWriteIndex$LAYOUT`, `beginningOfPassWriteIndex$OFFSET`)
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * * uint32_t beginningOfPassWriteIndex
     * * }
     */
    fun beginningOfPassWriteIndex(struct: MemorySegment, fieldValue: Int) {
        struct.set(`beginningOfPassWriteIndex$LAYOUT`, `beginningOfPassWriteIndex$OFFSET`, fieldValue)
    }

    private val `endOfPassWriteIndex$LAYOUT` =
        `$LAYOUT`.select(groupElement("endOfPassWriteIndex")) as ValueLayout.OfInt

    /**
     * Layout for field:
     * {@snippet lang=c :
     * * uint32_t endOfPassWriteIndex
     * * }
     */
    fun `endOfPassWriteIndex$layout`(): ValueLayout.OfInt {
        return `endOfPassWriteIndex$LAYOUT`
    }

    private const val `endOfPassWriteIndex$OFFSET`: Long = 12

    /**
     * Offset for field:
     * {@snippet lang=c :
     * * uint32_t endOfPassWriteIndex
     * * }
     */
    fun `endOfPassWriteIndex$offset`(): Long {
        return `endOfPassWriteIndex$OFFSET`
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * * uint32_t endOfPassWriteIndex
     * * }
     */
    fun endOfPassWriteIndex(struct: MemorySegment): Int {
        return struct.get(`endOfPassWriteIndex$LAYOUT`, `endOfPassWriteIndex$OFFSET`)
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * * uint32_t endOfPassWriteIndex
     * * }
     */
    fun endOfPassWriteIndex(struct: MemorySegment, fieldValue: Int) {
        struct.set(`endOfPassWriteIndex$LAYOUT`, `endOfPassWriteIndex$OFFSET`, fieldValue)
    }

    /**
     * Obtains a slice of `arrayParam` which selects the array element at `index`.
     * The returned segment has address `arrayParam.address() + index * layout().byteSize()`
     */
    fun asSlice(array: MemorySegment, index: Long): MemorySegment {
        return array.asSlice(layout().byteSize() * index)
    }

    /**
     * The size (in bytes) of this struct
     */
    fun sizeof(): Long {
        return layout().byteSize()
    }

    /**
     * Allocate a segment of size `layout().byteSize()` using `allocator`
     */
    fun allocate(allocator: SegmentAllocator): MemorySegment {
        return allocator.allocate(layout())
    }

    /**
     * Allocate an array of size `elementCount` using `allocator`.
     * The returned segment has size `elementCount * layout().byteSize()`.
     */
    fun allocateArray(elementCount: Long, allocator: SegmentAllocator): MemorySegment {
        return allocator.allocate(sequenceLayout(elementCount, layout()))
    }

    /**
     * Reinterprets `addr` using target `arena` and `cleanupAction` (if any).
     * The returned segment has size `layout().byteSize()`
     */
    fun reinterpret(addr: MemorySegment, arena: Arena, cleanup: Consumer<MemorySegment?>): MemorySegment {
        return reinterpret(addr, 1, arena, cleanup)
    }

    /**
     * Reinterprets `addr` using target `arena` and `cleanupAction` (if any).
     * The returned segment has size `elementCount * layout().byteSize()`
     */
    fun reinterpret(
        addr: MemorySegment,
        elementCount: Long,
        arena: Arena,
        cleanup: Consumer<MemorySegment?>
    ): MemorySegment {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup)
    }
}

