// Generated by jextract
package io.ygdrasil.wgpu.internal.jna

import java.lang.foreign.AddressLayout
import java.lang.foreign.Arena
import java.lang.foreign.GroupLayout
import java.lang.foreign.MemoryLayout.Companion.sequenceLayout
import java.lang.foreign.MemoryLayout.Companion.structLayout
import java.lang.foreign.MemoryLayout.PathElement.groupElement
import java.lang.foreign.MemorySegment
import java.lang.foreign.SegmentAllocator
import java.util.function.Consumer

/**
 * {@snippet lang=c :
 * * struct WGPURenderPipelineDescriptor {
 * *     const WGPUChainedStruct *nextInChain;
 * *     const char *label;
 * *     WGPUPipelineLayout layout;
 * *     WGPUVertexState vertex;
 * *     WGPUPrimitiveState primitive;
 * *     const WGPUDepthStencilState *depthStencil;
 * *     WGPUMultisampleState multisample;
 * *     const WGPUFragmentState *fragment;
 * * }
 * * }
 */
object WGPURenderPipelineDescriptor {
    private val `$LAYOUT` = structLayout(
        wgpu_h.C_POINTER.withName("nextInChain"),
        wgpu_h.C_POINTER.withName("label"),
        wgpu_h.C_POINTER.withName("layout"),
        WGPUVertexState.layout().withName("vertex"),
        WGPUPrimitiveState.layout().withName("primitive"),
        wgpu_h.C_POINTER.withName("depthStencil"),
        WGPUMultisampleState.layout().withName("multisample"),
        wgpu_h.C_POINTER.withName("fragment")
    ).withName("WGPURenderPipelineDescriptor")

    /**
     * The layout of this struct
     */
    fun layout(): GroupLayout {
        return `$LAYOUT`
    }

    private val `nextInChain$LAYOUT`: AddressLayout = `$LAYOUT`.select(groupElement("nextInChain")) as AddressLayout

    /**
     * Layout for field:
     * {@snippet lang=c :
     * * const WGPUChainedStruct *nextInChain
     * * }
     */
    fun `nextInChain$layout`(): AddressLayout {
        return `nextInChain$LAYOUT`
    }

    private const val `nextInChain$OFFSET`: Long = 0

    /**
     * Offset for field:
     * {@snippet lang=c :
     * * const WGPUChainedStruct *nextInChain
     * * }
     */
    fun `nextInChain$offset`(): Long {
        return `nextInChain$OFFSET`
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * * const WGPUChainedStruct *nextInChain
     * * }
     */
    fun nextInChain(struct: MemorySegment): MemorySegment {
        return struct.get(`nextInChain$LAYOUT`, `nextInChain$OFFSET`)
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * * const WGPUChainedStruct *nextInChain
     * * }
     */
    fun nextInChain(struct: MemorySegment, fieldValue: MemorySegment?) {
        struct.set(
            `nextInChain$LAYOUT`, `nextInChain$OFFSET`,
            fieldValue!!
        )
    }

    private val `label$LAYOUT`: AddressLayout = `$LAYOUT`.select(groupElement("label")) as AddressLayout

    /**
     * Layout for field:
     * {@snippet lang=c :
     * * const char *label
     * * }
     */
    fun `label$layout`(): AddressLayout {
        return `label$LAYOUT`
    }

    private const val `label$OFFSET`: Long = 8

    /**
     * Offset for field:
     * {@snippet lang=c :
     * * const char *label
     * * }
     */
    fun `label$offset`(): Long {
        return `label$OFFSET`
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * * const char *label
     * * }
     */
    fun label(struct: MemorySegment): MemorySegment {
        return struct.get(`label$LAYOUT`, `label$OFFSET`)
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * * const char *label
     * * }
     */
    fun label(struct: MemorySegment, fieldValue: MemorySegment?) {
        struct.set(
            `label$LAYOUT`, `label$OFFSET`,
            fieldValue!!
        )
    }

    private val `layout$LAYOUT`: AddressLayout = `$LAYOUT`.select(groupElement("layout")) as AddressLayout

    /**
     * Layout for field:
     * {@snippet lang=c :
     * * WGPUPipelineLayout layout
     * * }
     */
    fun `layout$layout`(): AddressLayout {
        return `layout$LAYOUT`
    }

    private const val `layout$OFFSET`: Long = 16

    /**
     * Offset for field:
     * {@snippet lang=c :
     * * WGPUPipelineLayout layout
     * * }
     */
    fun `layout$offset`(): Long {
        return `layout$OFFSET`
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * * WGPUPipelineLayout layout
     * * }
     */
    fun layout(struct: MemorySegment): MemorySegment {
        return struct.get(`layout$LAYOUT`, `layout$OFFSET`)
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * * WGPUPipelineLayout layout
     * * }
     */
    fun layout(struct: MemorySegment, fieldValue: MemorySegment?) {
        struct.set(
            `layout$LAYOUT`, `layout$OFFSET`,
            fieldValue!!
        )
    }

    private val `vertex$LAYOUT` = `$LAYOUT`.select(groupElement("vertex")) as GroupLayout

    /**
     * Layout for field:
     * {@snippet lang=c :
     * * WGPUVertexState vertex
     * * }
     */
    fun `vertex$layout`(): GroupLayout {
        return `vertex$LAYOUT`
    }

    private const val `vertex$OFFSET`: Long = 24

    /**
     * Offset for field:
     * {@snippet lang=c :
     * * WGPUVertexState vertex
     * * }
     */
    fun `vertex$offset`(): Long {
        return `vertex$OFFSET`
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * * WGPUVertexState vertex
     * * }
     */
    fun vertex(struct: MemorySegment): MemorySegment {
        return struct.asSlice(`vertex$OFFSET`, `vertex$LAYOUT`.byteSize())
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * * WGPUVertexState vertex
     * * }
     */
    fun vertex(struct: MemorySegment?, fieldValue: MemorySegment?) {
        MemorySegment.copy(
            fieldValue!!, 0L,
            struct!!, `vertex$OFFSET`, `vertex$LAYOUT`.byteSize()
        )
    }

    private val `primitive$LAYOUT` = `$LAYOUT`.select(groupElement("primitive")) as GroupLayout

    /**
     * Layout for field:
     * {@snippet lang=c :
     * * WGPUPrimitiveState primitive
     * * }
     */
    fun `primitive$layout`(): GroupLayout {
        return `primitive$LAYOUT`
    }

    private const val `primitive$OFFSET`: Long = 80

    /**
     * Offset for field:
     * {@snippet lang=c :
     * * WGPUPrimitiveState primitive
     * * }
     */
    fun `primitive$offset`(): Long {
        return `primitive$OFFSET`
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * * WGPUPrimitiveState primitive
     * * }
     */
    fun primitive(struct: MemorySegment): MemorySegment {
        return struct.asSlice(`primitive$OFFSET`, `primitive$LAYOUT`.byteSize())
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * * WGPUPrimitiveState primitive
     * * }
     */
    fun primitive(struct: MemorySegment?, fieldValue: MemorySegment?) {
        MemorySegment.copy(
            fieldValue!!, 0L,
            struct!!, `primitive$OFFSET`, `primitive$LAYOUT`.byteSize()
        )
    }

    private val `depthStencil$LAYOUT`: AddressLayout = `$LAYOUT`.select(groupElement("depthStencil")) as AddressLayout

    /**
     * Layout for field:
     * {@snippet lang=c :
     * * const WGPUDepthStencilState *depthStencil
     * * }
     */
    fun `depthStencil$layout`(): AddressLayout {
        return `depthStencil$LAYOUT`
    }

    private const val `depthStencil$OFFSET`: Long = 104

    /**
     * Offset for field:
     * {@snippet lang=c :
     * * const WGPUDepthStencilState *depthStencil
     * * }
     */
    fun `depthStencil$offset`(): Long {
        return `depthStencil$OFFSET`
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * * const WGPUDepthStencilState *depthStencil
     * * }
     */
    fun depthStencil(struct: MemorySegment): MemorySegment {
        return struct.get(`depthStencil$LAYOUT`, `depthStencil$OFFSET`)
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * * const WGPUDepthStencilState *depthStencil
     * * }
     */
    fun depthStencil(struct: MemorySegment, fieldValue: MemorySegment?) {
        struct.set(
            `depthStencil$LAYOUT`, `depthStencil$OFFSET`,
            fieldValue!!
        )
    }

    private val `multisample$LAYOUT` = `$LAYOUT`.select(groupElement("multisample")) as GroupLayout

    /**
     * Layout for field:
     * {@snippet lang=c :
     * * WGPUMultisampleState multisample
     * * }
     */
    fun `multisample$layout`(): GroupLayout {
        return `multisample$LAYOUT`
    }

    private const val `multisample$OFFSET`: Long = 112

    /**
     * Offset for field:
     * {@snippet lang=c :
     * * WGPUMultisampleState multisample
     * * }
     */
    fun `multisample$offset`(): Long {
        return `multisample$OFFSET`
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * * WGPUMultisampleState multisample
     * * }
     */
    fun multisample(struct: MemorySegment): MemorySegment {
        return struct.asSlice(`multisample$OFFSET`, `multisample$LAYOUT`.byteSize())
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * * WGPUMultisampleState multisample
     * * }
     */
    fun multisample(struct: MemorySegment?, fieldValue: MemorySegment?) {
        MemorySegment.copy(
            fieldValue!!, 0L,
            struct!!, `multisample$OFFSET`, `multisample$LAYOUT`.byteSize()
        )
    }

    private val `fragment$LAYOUT`: AddressLayout = `$LAYOUT`.select(groupElement("fragment")) as AddressLayout

    /**
     * Layout for field:
     * {@snippet lang=c :
     * * const WGPUFragmentState *fragment
     * * }
     */
    fun `fragment$layout`(): AddressLayout {
        return `fragment$LAYOUT`
    }

    private const val `fragment$OFFSET`: Long = 136

    /**
     * Offset for field:
     * {@snippet lang=c :
     * * const WGPUFragmentState *fragment
     * * }
     */
    fun `fragment$offset`(): Long {
        return `fragment$OFFSET`
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * * const WGPUFragmentState *fragment
     * * }
     */
    fun fragment(struct: MemorySegment): MemorySegment {
        return struct.get(`fragment$LAYOUT`, `fragment$OFFSET`)
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * * const WGPUFragmentState *fragment
     * * }
     */
    fun fragment(struct: MemorySegment, fieldValue: MemorySegment?) {
        struct.set(
            `fragment$LAYOUT`, `fragment$OFFSET`,
            fieldValue!!
        )
    }

    /**
     * Obtains a slice of `arrayParam` which selects the array element at `index`.
     * The returned segment has address `arrayParam.address() + index * layout().byteSize()`
     */
    fun asSlice(array: MemorySegment, index: Long): MemorySegment {
        return array.asSlice(layout().byteSize() * index)
    }

    /**
     * The size (in bytes) of this struct
     */
    fun sizeof(): Long {
        return layout().byteSize()
    }

    /**
     * Allocate a segment of size `layout().byteSize()` using `allocator`
     */
    fun allocate(allocator: SegmentAllocator): MemorySegment {
        return allocator.allocate(layout())
    }

    /**
     * Allocate an array of size `elementCount` using `allocator`.
     * The returned segment has size `elementCount * layout().byteSize()`.
     */
    fun allocateArray(elementCount: Long, allocator: SegmentAllocator): MemorySegment {
        return allocator.allocate(sequenceLayout(elementCount, layout()))
    }

    /**
     * Reinterprets `addr` using target `arena` and `cleanupAction` (if any).
     * The returned segment has size `layout().byteSize()`
     */
    fun reinterpret(addr: MemorySegment, arena: Arena, cleanup: Consumer<MemorySegment?>): MemorySegment {
        return reinterpret(addr, 1, arena, cleanup)
    }

    /**
     * Reinterprets `addr` using target `arena` and `cleanupAction` (if any).
     * The returned segment has size `elementCount * layout().byteSize()`
     */
    fun reinterpret(
        addr: MemorySegment,
        elementCount: Long,
        arena: Arena,
        cleanup: Consumer<MemorySegment?>
    ): MemorySegment {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup)
    }
}

