// Generated by jextract
package io.ygdrasil.wgpu.internal.jna

import java.lang.foreign.Arena
import java.lang.foreign.GroupLayout
import java.lang.foreign.MemoryLayout.Companion.paddingLayout
import java.lang.foreign.MemoryLayout.Companion.sequenceLayout
import java.lang.foreign.MemoryLayout.Companion.structLayout
import java.lang.foreign.MemoryLayout.PathElement.groupElement
import java.lang.foreign.MemorySegment
import java.lang.foreign.SegmentAllocator
import java.lang.foreign.ValueLayout
import java.util.function.Consumer

/**
 * {@snippet lang=c :
 * * struct WGPUVertexAttribute {
 * *     WGPUVertexFormat format;
 * *     uint64_t offset;
 * *     uint32_t shaderLocation;
 * * }
 * * }
 */
object WGPUVertexAttribute {
    private val `$LAYOUT` = structLayout(
        wgpu_h.C_INT.withName("format"),
        paddingLayout(4),
        wgpu_h.C_LONG_LONG.withName("offset"),
        wgpu_h.C_INT.withName("shaderLocation"),
        paddingLayout(4)
    ).withName("WGPUVertexAttribute")

    /**
     * The layout of this struct
     */
    fun layout(): GroupLayout {
        return `$LAYOUT`
    }

    private val `format$LAYOUT` = `$LAYOUT`.select(groupElement("format")) as ValueLayout.OfInt

    /**
     * Layout for field:
     * {@snippet lang=c :
     * * WGPUVertexFormat format
     * * }
     */
    fun `format$layout`(): ValueLayout.OfInt {
        return `format$LAYOUT`
    }

    private const val `format$OFFSET`: Long = 0

    /**
     * Offset for field:
     * {@snippet lang=c :
     * * WGPUVertexFormat format
     * * }
     */
    fun `format$offset`(): Long {
        return `format$OFFSET`
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * * WGPUVertexFormat format
     * * }
     */
    fun format(struct: MemorySegment): Int {
        return struct.get(`format$LAYOUT`, `format$OFFSET`)
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * * WGPUVertexFormat format
     * * }
     */
    fun format(struct: MemorySegment, fieldValue: Int) {
        struct.set(`format$LAYOUT`, `format$OFFSET`, fieldValue)
    }

    private val `offset$LAYOUT` = `$LAYOUT`.select(groupElement("offset")) as ValueLayout.OfLong

    /**
     * Layout for field:
     * {@snippet lang=c :
     * * uint64_t offset
     * * }
     */
    fun `offset$layout`(): ValueLayout.OfLong {
        return `offset$LAYOUT`
    }

    private const val `offset$OFFSET`: Long = 8

    /**
     * Offset for field:
     * {@snippet lang=c :
     * * uint64_t offset
     * * }
     */
    fun `offset$offset`(): Long {
        return `offset$OFFSET`
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * * uint64_t offset
     * * }
     */
    fun offset(struct: MemorySegment): Long {
        return struct.get(`offset$LAYOUT`, `offset$OFFSET`)
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * * uint64_t offset
     * * }
     */
    fun offset(struct: MemorySegment, fieldValue: Long) {
        struct.set(`offset$LAYOUT`, `offset$OFFSET`, fieldValue)
    }

    private val `shaderLocation$LAYOUT` = `$LAYOUT`.select(groupElement("shaderLocation")) as ValueLayout.OfInt

    /**
     * Layout for field:
     * {@snippet lang=c :
     * * uint32_t shaderLocation
     * * }
     */
    fun `shaderLocation$layout`(): ValueLayout.OfInt {
        return `shaderLocation$LAYOUT`
    }

    private const val `shaderLocation$OFFSET`: Long = 16

    /**
     * Offset for field:
     * {@snippet lang=c :
     * * uint32_t shaderLocation
     * * }
     */
    fun `shaderLocation$offset`(): Long {
        return `shaderLocation$OFFSET`
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * * uint32_t shaderLocation
     * * }
     */
    fun shaderLocation(struct: MemorySegment): Int {
        return struct.get(`shaderLocation$LAYOUT`, `shaderLocation$OFFSET`)
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * * uint32_t shaderLocation
     * * }
     */
    fun shaderLocation(struct: MemorySegment, fieldValue: Int) {
        struct.set(`shaderLocation$LAYOUT`, `shaderLocation$OFFSET`, fieldValue)
    }

    /**
     * Obtains a slice of `arrayParam` which selects the array element at `index`.
     * The returned segment has address `arrayParam.address() + index * layout().byteSize()`
     */
    fun asSlice(array: MemorySegment, index: Long): MemorySegment {
        return array.asSlice(layout().byteSize() * index)
    }

    /**
     * The size (in bytes) of this struct
     */
    fun sizeof(): Long {
        return layout().byteSize()
    }

    /**
     * Allocate a segment of size `layout().byteSize()` using `allocator`
     */
    fun allocate(allocator: SegmentAllocator): MemorySegment {
        return allocator.allocate(layout())
    }

    /**
     * Allocate an array of size `elementCount` using `allocator`.
     * The returned segment has size `elementCount * layout().byteSize()`.
     */
    fun allocateArray(elementCount: Long, allocator: SegmentAllocator): MemorySegment {
        return allocator.allocate(sequenceLayout(elementCount, layout()))
    }

    /**
     * Reinterprets `addr` using target `arena` and `cleanupAction` (if any).
     * The returned segment has size `layout().byteSize()`
     */
    fun reinterpret(addr: MemorySegment, arena: Arena, cleanup: Consumer<MemorySegment?>): MemorySegment {
        return reinterpret(addr, 1, arena, cleanup)
    }

    /**
     * Reinterprets `addr` using target `arena` and `cleanupAction` (if any).
     * The returned segment has size `elementCount * layout().byteSize()`
     */
    fun reinterpret(
        addr: MemorySegment,
        elementCount: Long,
        arena: Arena,
        cleanup: Consumer<MemorySegment?>
    ): MemorySegment {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup)
    }
}

