// Generated by jextract
package io.ygdrasil.wgpu.internal.jna

import java.lang.foreign.Arena
import java.lang.foreign.GroupLayout
import java.lang.foreign.MemoryLayout.Companion.sequenceLayout
import java.lang.foreign.MemoryLayout.Companion.structLayout
import java.lang.foreign.MemoryLayout.PathElement.groupElement
import java.lang.foreign.MemorySegment
import java.lang.foreign.SegmentAllocator
import java.util.function.Consumer

/**
 * {@snippet lang=c :
 * * struct WGPUBlendState {
 * *     WGPUBlendComponent color;
 * *     WGPUBlendComponent alpha;
 * * }
 * * }
 */
object WGPUBlendState {
    private val `$LAYOUT` = structLayout(
        WGPUBlendComponent.layout().withName("color"),
        WGPUBlendComponent.layout().withName("alpha")
    ).withName("WGPUBlendState")

    /**
     * The layout of this struct
     */
    fun layout(): GroupLayout {
        return `$LAYOUT`
    }

    private val `color$LAYOUT` = `$LAYOUT`.select(groupElement("color")) as GroupLayout

    /**
     * Layout for field:
     * {@snippet lang=c :
     * * WGPUBlendComponent color
     * * }
     */
    fun `color$layout`(): GroupLayout {
        return `color$LAYOUT`
    }

    private const val `color$OFFSET`: Long = 0

    /**
     * Offset for field:
     * {@snippet lang=c :
     * * WGPUBlendComponent color
     * * }
     */
    fun `color$offset`(): Long {
        return `color$OFFSET`
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * * WGPUBlendComponent color
     * * }
     */
    fun color(struct: MemorySegment): MemorySegment {
        return struct.asSlice(`color$OFFSET`, `color$LAYOUT`.byteSize())
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * * WGPUBlendComponent color
     * * }
     */
    fun color(struct: MemorySegment?, fieldValue: MemorySegment?) {
        MemorySegment.copy(
            fieldValue!!, 0L,
            struct!!, `color$OFFSET`, `color$LAYOUT`.byteSize()
        )
    }

    private val `alpha$LAYOUT` = `$LAYOUT`.select(groupElement("alpha")) as GroupLayout

    /**
     * Layout for field:
     * {@snippet lang=c :
     * * WGPUBlendComponent alpha
     * * }
     */
    fun `alpha$layout`(): GroupLayout {
        return `alpha$LAYOUT`
    }

    private const val `alpha$OFFSET`: Long = 12

    /**
     * Offset for field:
     * {@snippet lang=c :
     * * WGPUBlendComponent alpha
     * * }
     */
    fun `alpha$offset`(): Long {
        return `alpha$OFFSET`
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * * WGPUBlendComponent alpha
     * * }
     */
    fun alpha(struct: MemorySegment): MemorySegment {
        return struct.asSlice(`alpha$OFFSET`, `alpha$LAYOUT`.byteSize())
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * * WGPUBlendComponent alpha
     * * }
     */
    fun alpha(struct: MemorySegment?, fieldValue: MemorySegment?) {
        MemorySegment.copy(
            fieldValue!!, 0L,
            struct!!, `alpha$OFFSET`, `alpha$LAYOUT`.byteSize()
        )
    }

    /**
     * Obtains a slice of `arrayParam` which selects the array element at `index`.
     * The returned segment has address `arrayParam.address() + index * layout().byteSize()`
     */
    fun asSlice(array: MemorySegment, index: Long): MemorySegment {
        return array.asSlice(layout().byteSize() * index)
    }

    /**
     * The size (in bytes) of this struct
     */
    fun sizeof(): Long {
        return layout().byteSize()
    }

    /**
     * Allocate a segment of size `layout().byteSize()` using `allocator`
     */
    fun allocate(allocator: SegmentAllocator): MemorySegment {
        return allocator.allocate(layout())
    }

    /**
     * Allocate an array of size `elementCount` using `allocator`.
     * The returned segment has size `elementCount * layout().byteSize()`.
     */
    fun allocateArray(elementCount: Long, allocator: SegmentAllocator): MemorySegment {
        return allocator.allocate(sequenceLayout(elementCount, layout()))
    }

    /**
     * Reinterprets `addr` using target `arena` and `cleanupAction` (if any).
     * The returned segment has size `layout().byteSize()`
     */
    fun reinterpret(addr: MemorySegment, arena: Arena, cleanup: Consumer<MemorySegment?>): MemorySegment {
        return reinterpret(addr, 1, arena, cleanup)
    }

    /**
     * Reinterprets `addr` using target `arena` and `cleanupAction` (if any).
     * The returned segment has size `elementCount * layout().byteSize()`
     */
    fun reinterpret(
        addr: MemorySegment,
        elementCount: Long,
        arena: Arena,
        cleanup: Consumer<MemorySegment?>
    ): MemorySegment {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup)
    }
}

