// Generated by jextract
package io.ygdrasil.wgpu.internal.jna

import java.lang.foreign.AddressLayout
import java.lang.foreign.Arena
import java.lang.foreign.GroupLayout
import java.lang.foreign.MemoryLayout.Companion.paddingLayout
import java.lang.foreign.MemoryLayout.Companion.sequenceLayout
import java.lang.foreign.MemoryLayout.Companion.structLayout
import java.lang.foreign.MemoryLayout.PathElement.groupElement
import java.lang.foreign.MemorySegment
import java.lang.foreign.SegmentAllocator
import java.lang.foreign.ValueLayout
import java.util.function.Consumer

/**
 * {@snippet lang=c :
 * * struct WGPURequestAdapterOptions {
 * *     const WGPUChainedStruct *nextInChain;
 * *     WGPUSurface compatibleSurface;
 * *     WGPUPowerPreference powerPreference;
 * *     WGPUBackendType backendType;
 * *     WGPUBool forceFallbackAdapter;
 * * }
 * * }
 */
object WGPURequestAdapterOptions {
    private val `$LAYOUT` = structLayout(
        wgpu_h.C_POINTER.withName("nextInChain"),
        wgpu_h.C_POINTER.withName("compatibleSurface"),
        wgpu_h.C_INT.withName("powerPreference"),
        wgpu_h.C_INT.withName("backendType"),
        wgpu_h.C_INT.withName("forceFallbackAdapter"),
        paddingLayout(4)
    ).withName("WGPURequestAdapterOptions")

    /**
     * The layout of this struct
     */
    fun layout(): GroupLayout {
        return `$LAYOUT`
    }

    private val `nextInChain$LAYOUT`: AddressLayout = `$LAYOUT`.select(groupElement("nextInChain")) as AddressLayout

    /**
     * Layout for field:
     * {@snippet lang=c :
     * * const WGPUChainedStruct *nextInChain
     * * }
     */
    fun `nextInChain$layout`(): AddressLayout {
        return `nextInChain$LAYOUT`
    }

    private const val `nextInChain$OFFSET`: Long = 0

    /**
     * Offset for field:
     * {@snippet lang=c :
     * * const WGPUChainedStruct *nextInChain
     * * }
     */
    fun `nextInChain$offset`(): Long {
        return `nextInChain$OFFSET`
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * * const WGPUChainedStruct *nextInChain
     * * }
     */
    fun nextInChain(struct: MemorySegment): MemorySegment {
        return struct.get(`nextInChain$LAYOUT`, `nextInChain$OFFSET`)
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * * const WGPUChainedStruct *nextInChain
     * * }
     */
    fun nextInChain(struct: MemorySegment, fieldValue: MemorySegment?) {
        struct.set(
            `nextInChain$LAYOUT`, `nextInChain$OFFSET`,
            fieldValue!!
        )
    }

    private val `compatibleSurface$LAYOUT`: AddressLayout =
        `$LAYOUT`.select(groupElement("compatibleSurface")) as AddressLayout

    /**
     * Layout for field:
     * {@snippet lang=c :
     * * WGPUSurface compatibleSurface
     * * }
     */
    fun `compatibleSurface$layout`(): AddressLayout {
        return `compatibleSurface$LAYOUT`
    }

    private const val `compatibleSurface$OFFSET`: Long = 8

    /**
     * Offset for field:
     * {@snippet lang=c :
     * * WGPUSurface compatibleSurface
     * * }
     */
    fun `compatibleSurface$offset`(): Long {
        return `compatibleSurface$OFFSET`
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * * WGPUSurface compatibleSurface
     * * }
     */
    fun compatibleSurface(struct: MemorySegment): MemorySegment {
        return struct.get(`compatibleSurface$LAYOUT`, `compatibleSurface$OFFSET`)
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * * WGPUSurface compatibleSurface
     * * }
     */
    fun compatibleSurface(struct: MemorySegment, fieldValue: MemorySegment?) {
        struct.set(
            `compatibleSurface$LAYOUT`, `compatibleSurface$OFFSET`,
            fieldValue!!
        )
    }

    private val `powerPreference$LAYOUT` = `$LAYOUT`.select(groupElement("powerPreference")) as ValueLayout.OfInt

    /**
     * Layout for field:
     * {@snippet lang=c :
     * * WGPUPowerPreference powerPreference
     * * }
     */
    fun `powerPreference$layout`(): ValueLayout.OfInt {
        return `powerPreference$LAYOUT`
    }

    private const val `powerPreference$OFFSET`: Long = 16

    /**
     * Offset for field:
     * {@snippet lang=c :
     * * WGPUPowerPreference powerPreference
     * * }
     */
    fun `powerPreference$offset`(): Long {
        return `powerPreference$OFFSET`
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * * WGPUPowerPreference powerPreference
     * * }
     */
    fun powerPreference(struct: MemorySegment): Int {
        return struct.get(`powerPreference$LAYOUT`, `powerPreference$OFFSET`)
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * * WGPUPowerPreference powerPreference
     * * }
     */
    fun powerPreference(struct: MemorySegment, fieldValue: Int) {
        struct.set(`powerPreference$LAYOUT`, `powerPreference$OFFSET`, fieldValue)
    }

    private val `backendType$LAYOUT` = `$LAYOUT`.select(groupElement("backendType")) as ValueLayout.OfInt

    /**
     * Layout for field:
     * {@snippet lang=c :
     * * WGPUBackendType backendType
     * * }
     */
    fun `backendType$layout`(): ValueLayout.OfInt {
        return `backendType$LAYOUT`
    }

    private const val `backendType$OFFSET`: Long = 20

    /**
     * Offset for field:
     * {@snippet lang=c :
     * * WGPUBackendType backendType
     * * }
     */
    fun `backendType$offset`(): Long {
        return `backendType$OFFSET`
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * * WGPUBackendType backendType
     * * }
     */
    fun backendType(struct: MemorySegment): Int {
        return struct.get(`backendType$LAYOUT`, `backendType$OFFSET`)
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * * WGPUBackendType backendType
     * * }
     */
    fun backendType(struct: MemorySegment, fieldValue: Int) {
        struct.set(`backendType$LAYOUT`, `backendType$OFFSET`, fieldValue)
    }

    private val `forceFallbackAdapter$LAYOUT` =
        `$LAYOUT`.select(groupElement("forceFallbackAdapter")) as ValueLayout.OfInt

    /**
     * Layout for field:
     * {@snippet lang=c :
     * * WGPUBool forceFallbackAdapter
     * * }
     */
    fun `forceFallbackAdapter$layout`(): ValueLayout.OfInt {
        return `forceFallbackAdapter$LAYOUT`
    }

    private const val `forceFallbackAdapter$OFFSET`: Long = 24

    /**
     * Offset for field:
     * {@snippet lang=c :
     * * WGPUBool forceFallbackAdapter
     * * }
     */
    fun `forceFallbackAdapter$offset`(): Long {
        return `forceFallbackAdapter$OFFSET`
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * * WGPUBool forceFallbackAdapter
     * * }
     */
    fun forceFallbackAdapter(struct: MemorySegment): Int {
        return struct.get(`forceFallbackAdapter$LAYOUT`, `forceFallbackAdapter$OFFSET`)
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * * WGPUBool forceFallbackAdapter
     * * }
     */
    fun forceFallbackAdapter(struct: MemorySegment, fieldValue: Int) {
        struct.set(`forceFallbackAdapter$LAYOUT`, `forceFallbackAdapter$OFFSET`, fieldValue)
    }

    /**
     * Obtains a slice of `arrayParam` which selects the array element at `index`.
     * The returned segment has address `arrayParam.address() + index * layout().byteSize()`
     */
    fun asSlice(array: MemorySegment, index: Long): MemorySegment {
        return array.asSlice(layout().byteSize() * index)
    }

    /**
     * The size (in bytes) of this struct
     */
    fun sizeof(): Long {
        return layout().byteSize()
    }

    /**
     * Allocate a segment of size `layout().byteSize()` using `allocator`
     */
    fun allocate(allocator: SegmentAllocator): MemorySegment {
        return allocator.allocate(layout())
    }

    /**
     * Allocate an array of size `elementCount` using `allocator`.
     * The returned segment has size `elementCount * layout().byteSize()`.
     */
    fun allocateArray(elementCount: Long, allocator: SegmentAllocator): MemorySegment {
        return allocator.allocate(sequenceLayout(elementCount, layout()))
    }

    /**
     * Reinterprets `addr` using target `arena` and `cleanupAction` (if any).
     * The returned segment has size `layout().byteSize()`
     */
    fun reinterpret(addr: MemorySegment, arena: Arena, cleanup: Consumer<MemorySegment?>): MemorySegment {
        return reinterpret(addr, 1, arena, cleanup)
    }

    /**
     * Reinterprets `addr` using target `arena` and `cleanupAction` (if any).
     * The returned segment has size `elementCount * layout().byteSize()`
     */
    fun reinterpret(
        addr: MemorySegment,
        elementCount: Long,
        arena: Arena,
        cleanup: Consumer<MemorySegment?>
    ): MemorySegment {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup)
    }
}

