name: Publish wgpu4k snapshot

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version to publish'
        required: false
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 22
          cache: 'gradle'
      - name: Build and publish with Gradle
        run: ./gradlew fetch-native-dependencies publish --info
        env:
          SNAPSHOT: "true"
          VERSION: ${{ github.event.inputs.version }}
          SONATYPE_LOGIN: ${{ secrets.SONATYPE_LOGIN }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          PGP_PUBLIC: ${{ secrets.PGP_PUBLIC }}
          PGP_PRIVATE: ${{ secrets.PGP_PRIVATE }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}

